<?php
// This file generated by Propel 1.6.7.1 convert-conf target
return array (
  'BaseJQStoreManagedJob' => 'jqjobs/om/BaseJQStoreManagedJob.php',
  'BaseJQStoreManagedJobPeer' => 'jqjobs/om/BaseJQStoreManagedJobPeer.php',
  'BaseJQStoreManagedJobQuery' => 'jqjobs/om/BaseJQStoreManagedJobQuery.php',
  'JQStoreManagedJob' => 'jqjobs/JQStoreManagedJob.php',
  'JQStoreManagedJobPeer' => 'jqjobs/JQStoreManagedJobPeer.php',
  'JQStoreManagedJobQuery' => 'jqjobs/JQStoreManagedJobQuery.php',
  'JQStoreManagedJobTableMap' => 'jqjobs/map/JQStoreManagedJobTableMap.php',
);