<?php
// This file generated by Propel 1.6.7.1 convert-conf target
// from XML runtime conf file /Users/apinstein/dev/sandbox/jqjobs/propel-build/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'jqjobs' => 
    array (
      'adapter' => 'pgsql',
      'connection' => 
      array (
        'dsn' => 'pgsql:host=localhost;dbname=jqjobs_test;user=postgres'
        #'dsn' => 'pgsql:host=' . getenv('dbhost') . ';port=' . getenv('dbport') . ';dbname=' . getenv('db') . ';user=' . getenv('dbuser') . ';' . getenv('dbpassdsn')
      ),
    ),
    'default' => 'jqjobs',
  ),
  'generator_version' => '1.6.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-jqjobs-conf.php');
return $conf;
